# Generated by Django 4.0.6 on 2022-07-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('url', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('nom_original', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('url', models.SlugField()),
                ('nombres_saisons', models.IntegerField()),
                ('status_anime', models.BooleanField()),
                ('status', models.BooleanField()),
                ('image', models.SlugField()),
                ('plateforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plateforme')),
            ],
        ),
    ]
