# Generated by Django 4.0.6 on 2022-07-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animes',
            new_name='Anime',
        ),
    ]
