# Generated by Django 4.0.6 on 2022-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_anime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anime_image'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='nom_original',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status_anime',
            field=models.BooleanField(default=False),
        ),
    ]
