# Generated by Django 4.0.6 on 2022-07-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_anime_description_alter_anime_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='nombres_saisons',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='url',
            field=models.SlugField(null=True),
        ),
    ]
