# Generated by Django 4.0.6 on 2022-07-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_anime_nombres_saisons_alter_anime_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='plateforme_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='plateforme',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Plateforme',
        ),
    ]
