# Generated by Django 4.0.6 on 2022-07-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_plateforme_remove_anime_plateforme_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plateforme',
            name='plateforme',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='plateforme',
            name='plateforme_url',
            field=models.CharField(max_length=256),
        ),
    ]
