# Generated by Django 4.0.6 on 2022-07-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_plateforme_plateforme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='plateforme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='api.plateforme'),
        ),
    ]
