# Generated by Django 4.0.6 on 2022-07-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_anime_plateforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='plateforme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plateforme'),
        ),
    ]
