# Generated by Django 4.0.6 on 2022-07-31 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_alter_anime_plateforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='plateforme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='api.plateforme'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime', to=settings.AUTH_USER_MODEL),
        ),
    ]
