# Generated by Django 4.0.6 on 2022-08-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_anime_plateforme_alter_anime_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plateforme',
            old_name='plateforme',
            new_name='plateforme_name',
        ),
    ]
